import Head from "next/head";
import Link from 'next/link'
import Image from "next/image";
import styles from "../styles/Home.module.css";

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Ant</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <h1 className={styles.title}>
          Welcome to <a href="/">Ant!</a>
        </h1>
        <nav>
          <a href="/timeline">Anties</a>
        </nav>
      </main>
    </div>
  );
}
